### ISSUE TITLE
Error handling missing

### ISSUE THREAD

**Issue by ustulation** [maidsafe/self_encryption#183]
Trait functions which the user is supposed to handle, don't cater for errors. [Presently they look like this](https://github.com/maidsafe/self_encryption/blob/master/src/lib.rs#L351):
```
pub trait Storage {
    /// Fetch the data bearing the name
    fn get(&self, name: &[u8]) -> Vec<u8>;
    /// Insert the data bearing the name.
    fn put(&mut self, name: Vec<u8>, data: Vec<u8>);
}
```

So anyone implementing those and running into errors is stuck as there is no _proper_ value to return to SE. These traits should probably return S.E defined errors and S.E crate can then decide what to do in case of errors - either return immediately with and error or rollback if possible etc. That would be much cleaner.

**Comment by Fraser999** [comment]
Fixed by https://github.com/maidsafe/self_encryption/pull/185.
