### ISSUE TITLE
Bench tests give out of bounds error:

### ISSUE THREAD

**Issue by steveklabnik** [maidsafe/self_encryption#39]
```
$ cargo bench
     Running target/release/lib-a1c7f0b70117a838

running 5 tests
test bench_write_then_read_a_200B ... bench:     11708 ns/iter (+/- 532) = 34 MB/s
test bench_write_then_read_b_1KB  ... bench:     42412 ns/iter (+/- 3723) = 48 MB/s
test bench_write_then_read_c_1MB  ... thread '<main>' panicked at 'index out of bounds: the len is 1048576 but the index is 1048576', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1356
```

This is on Debian.

**Comment by dirvine** [comment]
Interesting what rustc --version is this with ?

**Comment by steveklabnik** [comment]
```
rustc 1.0.0-nightly (6b95d8bed 2015-04-09) (built 2015-04-10)
```

**Comment by dirvine** [comment]
yip confirmed with rustc 1.0.0-nightly (d9146bf8b 2015-04-07) (built 2015-04-08)
Happy you ignore that one for now and I will take a peek and push a fix.

**Comment by dirvine** [comment]
Yes a bug introduced in the read method, I have commented out that for now to let you check out bench and will commit a fix as soon as I figure out the issue. One of the guys working on it now. (frantic pace week :-) )

**Comment by dirvine** [comment]
weird, bench is OK till  rustc --version rustc 1.0.0-nightly (be9bd7c93 2015-04-05) (built 2015-04-06)

**Comment by benjaminbollen** [comment]
I updated from rustc from build 2015-04-06 to nightly 2015-04-10 and again benchmarks and tests pass.  Does it succeed for you on the latest nigthly?

**Comment by steveklabnik** [comment]
> (frantic pace week :-) )

Oh don't I know that feeling

**Comment by dirvine** [comment]
I bet! All good though

**Comment by Fraser999** [comment]
Benchmark tests all pass with current code.
