### ISSUE TITLE
Missing documentation page

### ISSUE THREAD

**Issue by DoumanAsh** [maidsafe/self_encryption#92]
Crate provides you with http://maidsafe.net/self_encryption/self_encryption/latest
But it is actually http://maidsafe.net/self_encryption/0.2.0/self_encryption/index.html ?

**Comment by Fraser999** [comment]
Thanks for the report.

This should be fixed once https://github.com/maidsafe/self_encryption/pull/93 gets merged and pushed to crates.

**Comment by Fraser999** [comment]
#93 is now merged.
